### DISCUSSION TITLE
rust写的maa命令行工具

### DISCUSSION THREAD

**Discussion by wangl-cc** [MaaAssistantArknights/MaaAssistantArknights#6063] [Show and tell]
Linux使用maa比较困难，目前的方法主要是写Python脚本来调用MaaCore，但是敲代码有一定门槛，并且更改起来比较麻烦，所以我用rust写了一个命令行工具[maa-cli](https://github.com/wangl-cc/maa-cli)，用来在Linux上使用Maa。因为Linux和macOS大多地方都是一样的，所有这个工具也支持mac（Intel，Arm都支持，但是不知道是哪里的bug，通过命令行打开PlayCover下的明日方舟可以登陆，但是无法获得作战记录）。Windows的话，一个我没有Windows设备，一个我也不懂Windows开发，所以我虽然尝试了支持Windows，但是始终不能编译通过，所以就放弃了（当然如果有大佬对这个项目有一点小小的兴趣来帮助支持Windows，我会非常感谢）。我本来是也是打算用Python写（如果用Python写可能就没有多平台支持的问题了），但是由于刚好我最近在学习rust，而且rust刚好有很好的工具库，就决定用这个项目当作练习。因为我是rust小白，写的可能有很多有问题的地方，所以欢迎各位大佬对项目提意见。

接下来言归正传，我来介绍一下我这个命令行工具的功能：

## 通过配置文件定义任务，并通过`maa run <task>`运行

这个工具的核心功能就是降低写代码的麻烦，但是我们需要写配置文件来配置我们一键收菜的时候干什么。

配置文件可以是TOML,YAML或者JSON，我个人更喜欢TOML来写配置，所以以TOML为例子.
一个任务文件包含多个子任务，每一个子任务是一个[MAA任务链](https://maa.plus/docs/3.1-%E9%9B%86%E6%88%90%E6%96%87%E6%A1%A3.html#asstappendtask)：
```toml
[[tasks]]
type = "StartUp" # maa任务的类型
params = { client_type = "Official", start_game_enabled = true } # maa任务的参数
```
如果你想要根据一些条件运行不同参数的任务，你可以定义多个任务的变体：
```toml
[[tasks]]
type = "Infrast"

[tasks.params]
mode = 10000
facility = ["Trade", "Reception", "Mfg", "Control", "Power", "Office", "Dorm"]
dorm_trust_enabled = true
filename = "normal.json" # 自定义的基建计划的文件名应该位于`$MAA_CONFIG_DIR/infrast`

# 在12:00:00之前使用计划1，在12:00:00到18:00:00之间使用计划2，在18:00:00之后使用计划0
[[tasks.variants]]
condition = { type = "Time", end = "12:00:00" } # 如果没有定义start，那么它将会是00:00:00
params = { plan_index = 1 }

[[tasks.variants]]
condition = { type = "Time", start = "12:00:00", end = "18:00:00" }
params = { plan_index = 2 }

[[tasks.variants]]
condition = { type = "Time", start = "18:00:00" }
params = { plan_index = 0 }
```
这里的`condition`字段用于确定哪一个变体应该被使用，而匹配的变体的`params`字段将会被合并到任务的主参数中。

**注意**：这个CLI不会读取基建计划文件中的任何内容，包括基建计划文件中定义的时间段，所以你必须在`condition`字段中定义时间段，来在不同的时间运行不同的基建计划。

除了`Time`条件，还有`DateTime`，`Weakday`和`Combined`（其他条件的组合）条件：
```toml
[[tasks]]
type = "Fight"

# 周一早上刷5次剿灭
[[tasks.variants]]
params = { "stage" = "Annihilation", times = 5 }
[tasks.variants.condition]
type = "Combined"
conditions = [
  { type = "Weekday", weekdays = ["Mon"] },
  { type = "Time", end = "12:00:00" },
]

# 在夏活期间，刷SL-8
[[tasks.variants]]
params = { stage = "SL-8" }
condition = { type = "DateTime", start = "2023-08-01T16:00:00", end = "2023-08-21T03:59:59" }

# 在夏活期间以外的周二、周四和周六，刷CE-6
[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Tue", "Thu", "Sat"] }
params = { stage = "CE-6" }

# 其他时间，刷1-7
[[tasks.variants]]
params = { stage = "1-7" }
```
如果有多个变体被匹配，第一个将会被使用。如果没有给出条件，那么变体将会总是被匹配，所以你可以把没有条件的变体放在最后，作为默认的情况。

如果没有变体被匹配，那么任务将不会被执行，这在你想要只在某些条件下运行任务时很有用：
```toml
# 只在在18:00:00之后进行信用商店相关的操作
[[tasks]]
type = "Mall"
[tasks.params]
shopping = true
credit_fight = true
buy_first = ["招聘许可", "龙门币"]
blacklist = ["碳", "家具", "加急许可"]
[[tasks.variants]]
condition = { type = "Time", start = "18:00:00" }
```

我自己用的配置文件你可以在[这里](https://github.com/wangl-cc/dotfiles/tree/master/.config/maa)找到。

## MaaCore消息处理

写Python脚本的另一个痛点就是没有现成的Callback，自己实现起来很麻烦，任务出问题了可能要去查log。这个CLI我参考WindowsGUI的消息处理，捏了一个我觉得还凑活的输出，并且可以通过`-v`和`-q`参数来改变消息等级（Log level)，从而实现减少或者增加消息。

这是`maa run daily -v`情况下的输出：
<img width="1440" alt="截屏2023-08-23 17 31 40" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40141251/501252b1-2ebc-4fdc-92ba-c4e7871e5a21">
有个问题就是没有本地化，可能有些消息不太好懂。

## 安装和更新MaaCore

`maa install [channel]` 和 `maa update [channel]`命令可以用来安装和更新MaaCore本身，这里的channel可以是stable，beta和alpha，stable就是下载并安装最新的稳定版，另外则是两个相应的beta和alpha，如果省略这个参数，默认是稳定版。这个下载是从maa的API来获取版本信息，并且对可用的镜像测速，最后选最快的下载，所以不用担心下不下来。

## 安装和更新这个工具本身

`maa self install` 和 `maa self update`用来安装和更新这个工具本身。这个工具本身包括两个部分`maa`和`maa-run`，前者是用来和用户交互的，后者是用来和MaaCore交互的。由于我不想让这个工具带着MaaCore本身一起发布（这样可以让两者分别单独更新)，而rust有没有办法在链接的库不存在的情况下运行，所以我把所有和MaaCore交互的库放在了`maa-run`里面。在安装的时候只需要下载`maa`这个工具然后用`maa self install`来安装`maa-run`。而`maa self update`会同时检查两个工具是否都是最新版，如果不是是就可以下载并安装相应的最新版。不过由于我这个工具没有镜像，版本信息和包都存在Github上，所以在国内可能会存在下不动的情况。这种情况一个可选的方法是找一个Github代理的网站，然后设置`MAA_CLI_API`和`MAA_CLI_DOWNLOAD`两个环境变量，比如这样:
```
export MAA_CLI_API=https://ghproxy.com/https://raw.githubusercontent.com/wangl-cc/maa-cli/version/version.json
export MAA_CLI_DOWNLOAD=https://ghproxy.com/https://github.com/wangl-cc/maa-cli/releases/download
maa self install
```

更多的其他部分细节，欢迎大家去[我的仓库](https://github.com/wangl-cc/maa-cli)查看。也希望这个小工具会对在Linux上使用MAA的小伙伴们有用。
