### ISSUE TITLE
使用项目提供的java示例无法在redroid13上唤醒游戏

### ISSUE THREAD

**Issue by flower-knight** [MaaAssistantArknights/MaaAssistantArknights#12722]
### 请确认自己完成了下列要求之后再进行勾选，若未完成但勾选将被直接关闭 Issue

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我使用的是当前更新版本的最新版，且已查看版本发布至今的 [更新内容](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commits/dev/) 和 [Pull Requests](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pulls) 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [x] 我已检查了[常见问题](https://maa.plus/docs/zh-cn/manual/faq.html)、[公告](/MaaAssistantArknights/MaaAssistantArknights/issues/7732)、[活跃议题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues)、[已关闭议题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues?q=is%3Aissue%20state%3Aclosed)，确认我的问题未被提及

### 问题描述

Ubuntu 24.04.1 LTS环境下，基于项目中的java简单操作示例稍作修改，流程改为从桌面唤醒游戏，对redroid11和redroid12都能成功唤醒，但在redroid13的情况下会任务失败，看输出日志似乎一直在截图，最后报任务链失败。在v5.15.6、v5.12.0版本下都进行测试，均无法操作redroid13，可以操作redroid12。作为对比，我基于项目提供的使用TypeScript操作maa的示例改造的JavaScript代码能在各个Maa版本下成功唤醒redroid11、12、13上的游戏

```java
  public class MaaJavaSample {
  
      /**
       * Maa的Java调用实例实现，最简示例仅需依赖第三方JNA库。
       * 仅在Windows下进行过测试，未在Linux下测试过(相信强大的Linux用户自己可以解决问题！
       * <p>
       * --------特别提醒----------
       * 1. 版本兼容性： >= v3.9.0-alpha。
       * 2. 需要手动在 我的电脑 - 高级系统设置 - 环境变量中，给Path增加Maa的路径。
       * --------特别提醒----------
       *
       * @param args
       */
      public static void main(String[] args) {
          String osName = System.getProperty("os.name");
  
          //设定JNA寻找maa的dll的地址，同时也要把这个路径添加到环境变量中的Path中！
          String maaPath = "/home/guest/env/maa/test";
          System.setProperty("jna.library.path", maaPath);
  
          System.out.println(System.getProperties());
          //adb地址，自己看着办
          String adbPath = "/home/guest/env/adb";
  
          //第一步，加载Maa调用实例，加载失败请检查jna.library.path和path参数
          MaaCore instance = Native.load("MaaCore", MaaCore.class);
          System.out.println("获取Maa版本号:" + instance.AsstGetVersion());
  
          //第二步，加载Maa资源初始化
          boolean b = instance.AsstLoadResource(maaPath);
          System.out.println("Maa加载:" + b);
  
          //第三步，创建实例
          //这一步可以多次创建多个实例连接如果你有多个模拟器
          Pointer pointer = instance.AsstCreate();
  //        Pointer pointer = instance.AsstCreateEx((msg, detail_json, custom_arg) -> {
  //            System.out.printf("回调msg : %s , 回调 detail_json : %s ,回调 custom_arg : %s \n", msg, detail_json, custom_arg);
  //        }, "瞎写的参数建议可以弄个自己生成的实例ID");
  
          boolean setTouchMode = instance.AsstSetInstanceOption(pointer, 2, "maatouch");
          System.out.println("Maa 设置触控模式:" + setTouchMode);
  
          //第四步，发起连接
          boolean adb = instance.AsstConnect(pointer, adbPath, "10.10.5.4:5555", "");
          System.out.println("Maa 尝试连接:" + adb);
  
          //第五步，添加任务，详细参数请参考Maa集成文档，此处示例为清理智，执行上次战斗
  //        instance.AsstAppendTask(pointer, "Fight", "{\"stage\":\"LastBattle\"}");
          instance.AsstAppendTask(pointer, "StartUp", "{\"client_type\":\"Official\",\"start_game_enabled\":true}");
  
          //开始执行
          instance.AsstStart(pointer);
          new Scanner(System.in).next();
  
          //停止执行，会清空taskChain
          instance.AsstStop(pointer);
  
          //销毁实例，释放连接
          instance.AsstDestroy(pointer);
      }
  
  
  }
  ```

### Version

MAA Version: v5.15.6、V5.12.0

### 日志和配置文件

[MaaJavaSample.zip](https://github.com/user-attachments/files/20248829/MaaJavaSample.zip)

[asst.v5.12.0.log](https://github.com/user-attachments/files/20254699/asst.v5.12.0.log)
v5.12.0版本日志后面有一截调用redroid12成功唤醒的日志

[asst.v5.15.6.log](https://github.com/user-attachments/files/20254723/asst.v5.15.6.log)

### 配置信息

- 运行环境：Ubuntu 24.04.1 LTS

- jdk版本：

  openjdk version "17" 2021-09-14
  OpenJDK Runtime Environment (build 17+35-2724)
  OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

- redroid12和13使用docker compose部署

  ```yaml
  services:
    redroid:
      image: ghcr.io/codysk/redroid:13_ndk
      tty: true
      stdin_open: true
      container_name: redroid13-test
      restart: unless-stopped
      privileged: true
      ports:
        - 5555:5555
      volumes:
        - ./data:/data
      command:
        - androidboot.redroid_virtual_wifi=1
        - persist.sys.nativebridge=1
        - androidboot.redroid_gpu_mode=guest
        - androidboot.redroid_fps=30
        - androidboot.use_memfd=1
        - ro.product.cpu.abilist=x86_64,x86,arm64-v8a
        - ro.product.cpu.abilist32=x86
        - ro.product.cpu.abilist64=x86_64,arm64-v8a
        - ro.dalvik.vm.isa.arm=x86
        - ro.dalvik.vm.isa.arm64=x86_64
        - ro.enable.native.bridge.exec=1
        - ro.enable.nativa.bridge.exec64=1
        - ro.build.fingerprint=google/kiwi_x86_64/vsoc_kiwi_x86_64:12/SKR1.230306.001.A3/9888534:user/release-keys
        - ro.dalvik.vm.native.bridge=libndk_translation.so
  ```

  ```
  services:
    redroid:
      image: ghcr.io/codysk/redroid:12_houdini
      #tty: true
      #stdin_open: true
      container_name: redroid12-lhn
      restart: unless-stopped
      privileged: true
      ports:
        - 5555:5555
      volumes:
        - ./data:/data
      command:
        - androidboot.redroid_virtual_wifi=1
        - persist.sys.nativebridge=1
        - androidboot.redroid_gpu_mode=auto
        - androidboot.redroid_fps=30
        - androidboot.use_memfd=1
        - ro.product.cpu.abilist=x86,armeabi-v7a,armeabi,x86_64,arm64-v8a
        - ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
        - ro.product.cpu.abilist64=x86_64,arm64-v8a
        - ro.dalvik.vm.isa.arm=x86
        - ro.dalvik.vm.isa.arm64=x86_64
        - ro.enable.native.bridge.exec=1
        - ro.enable.nativa.bridge.exec64=1
        - ro.build.fingerprint=google/kiwi_x86_64/vsoc_kiwi_x86_64:12/SKR1.230306.001.A3/9888534:user/release-keys
        - ro.dalvik.vm.native.bridge=libhoudini.so
  ```

- redroid11使用docker命令部署

  ```bash
  docker run -itd --privileged \
      --restart always \
      -v ~/data:/data \
      -p 5555:5555 \
      --name redroid11 \
      redroid/redroid:11.0.0-latest \
      androidboot.redroid_fps=30 \
      androidboot.redroid_width=720 \
      androidboot.redroid_height=1280 \
      androidboot.redroid_dpi=320 \
      androidboot.redroid_gpu_mode=guest \
      androidboot.use_memfd=true
  ```
