### ISSUE TITLE
[建议]添加Github action自动编译

### ISSUE THREAD

**Issue by zhongfly** [MaaAssistantArknights/MaaAssistantArknights#409]
可以在作者来不及或忘记发新版本时，让用户可以临时使用

大致可以这样:
```yaml
name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    name: "Build MaaAssistantArknights"
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Build
        shell: cmd
        run: |
          msbuild --restore
          msbuild MeoAssistantArknights.sln /m /p:Configuration=Release /p:Platform=x64
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: "MaaAssistantArknights"
          path: x64\Release\
```
